- mhkit/tests/test_river.py
- mhkit/tests/test_tidal.py
Added 3 tests:
1. river.io.request)usgs_data('Dailiy')
2. river.io.request)usgs_data('Instant')
3. tidial.io.request_noaa_data()
Note: Test 3 above calls on tidal.io._xml_to_dataframe
> Add test coverage for tidal and river IO

- mhkit/tests/test_wave.py
- mhkit/wave/resource.py
I believe I found a missing sqrt in the `waves.resource.surface_elevation` function (the time series of the surface elevation was too small). Fixed and added unit test. Here's the ad-hoc code I used to find the problem. 
```python
from mhkit import wave
import numpy as np
import matplotlib.pylab as plt
gamma = 9
Tp = 1/3
Hs = 5e-2
f_low = 2
f_high = 4
df = 1/30
f = np.arange(f_low, f_high, df)
S = wave.resource.jonswap_spectrum(f, Tp, Hs, gamma)
S.columns = ['orig.']
axs = S.plot(style='.-')
dt = 0.01
t = np.arange(0,2*60+dt,0.01)
eta = wave.resource.surface_elevation(S, t)
ax = eta.plot()
ax.set_xticks(np.arange(0,t[-1]+1/df,1/df))
Sn = wave.resource.elevation_spectrum(eta, 1/dt, int(np.floor(t[-1]/df)))
Sn.columns = ['from eta']
Sn.plot(ax=axs, style='.--', grid=True) …
```
> wave.resource.surface_elevation: add missing sqrt in  and unit test

- mhkit/tests/test_wave.py
- mhkit/wave/resource.py
Currently, you can set the random number generator feed for `surface_elevation` via the optional argument `seed`. However, it would also be nice to explicitly set the phases to some known values. This pull request provides this functionality via an additional optional argument `phases`.
https://github.com/MHKiT-Software/MHKiT-Python/blob/362f76b09ea411aae214c80df3d90f5eb4f02471/mhkit/wave/resource.py#L186
> Explicit phasing in surface_elevation (& add frequency_bins  opt)

- examples/river_example.ipynb
- examples/tidal_example.ipynb
Updating the link formatting to render in the documentation correctly. Once updated here this should pull into the documentation submodule.
> Change link formatting to render in documentation correctly

- mhkit/wave/resource.py
Try again with a clean commit history. This is to fix a bug in the recent wave.resource changes that allowed for Series to be passed. There was an oversight that the changes prevented multi-column data frames from being passed- which broke our example notebook.
> Bug series

- mhkit/tests/test_utils.py
- mhkit/utils.py
Simple function to calculate the magnitude and phase of floats, ints, arrays, or series in 2D or 3D added to the utils module.
@kmruehl do you think you will have time to take a look at this before your vacation?
> Adding magnitude and phase function

- mhkit/tests/test_wave.py
- mhkit/wave/resource.py
> Fix wave elevation function.

- examples/extreme_response_full_sea_state_example.ipynb
- mhkit/loads/extreme.py
- mhkit/tests/loads/test_loads.py
This PR adds a function called `return_year_value`. An example usage can be seen in the `extreme_response_full_sea_state_example.ipynb`. The example would be adjusted from:
To:
With the `return_year_value` function defined as follows:
```
def return_year_value(ppf, return_year, short_term_period_hr):
"""
Calculate the value from a given distribution corresponding to
a particular return year.
Parameters
----------
ppf: callable function of 1 argument
Percentage Point Function (inverse CDF) of short term distribution.
return_year: int
Return period in years.
short_term_period_hr: int, float
Short term period the distribution is created from in hours.
Returns
-------
value: float
The value corresponding to the return period from the distribution.
"""
assert callable(ppf)
assert …
```
> Add function to compute value at a given return period

- .github/workflows/main.yml
Currently, we are not running tests when pushing to the Develop branch.
This will enable CI tests on push to the Develop branch
> Run CI on push to Develop

- mhkit/tests/wave/test_resource_metrics.py
- mhkit/wave/resource.py
> Provide function to convert from Te to Tp using ITTC approximation

- mhkit/loads/extreme.py
- mhkit/tests/loads/test_loads.py
In an oversight in merging #193 the docstring was updated for the type of return_year in return_year_value but the corresponding assertion was not.
Tests for the types of the two input parameters have been added to try to avoid a simular situation occuring the future.
> Fix type for return_year in extreme.return_year_value

- mhkit/river/io/d3d.py
With Delft3D newest update the variable names have been updated to include "mesh_2d" . This PR is backward compatible with older versions of Delft3D files. 
Currently functions get_layer_data and get_all_data_points have been updated.
#237
> Delft3D updates 

- .github/workflows/pypi.yml
- README.md
This PR adds a github actions workflow that releases to test.pypi.org on every commit to master and to pypi.org on every published release. It requires setting two repository secrets:
1. TEST_PYPI_API_TOKEN
2. PYPI_API_TOKEN
I also updated the badges in the README to use html `img` tags instead of markdown so that they will show up correctly on pypi.org. Previously it looked like this:
> Release to pypi github actions workflow

- .github/workflows/main.yml
This Pull Request introduces a mechanism to selectively trigger the execution of expensive hindcast tests based on the context of the changes made. Specifically, the hindcast tests will only run under two scenarios:
1. If there are changes made to the modules within the `mhkit/wave/io/hindcast` directory.
2. If the merge request is targeted at the `master` branch.
To achieve this, a new job named `check-changes` has been added to the workflow, which precedes the `prepare-cache` job.
Here's how the check-changes job operates:
1. Detecting Module Changes:
- Check if any files within the `mhkit/wave/io/hindcast` directory have been altered.
- If yes, set `wave_io_hindcast_changed` to true.
- If no, set `wave_io_hindcast_changed` to false.
2. Determining Hindcast Test Execution:
- Check if …
> Run hindcast tests only on change to hindcast module

- mhkit/loads/extreme.py
- mhkit/loads/general.py
- mhkit/tests/loads/test_loads.py
> Convert loads module to xarray

- mhkit/dolfyn/io/nortek.py
- mhkit/dolfyn/io/nortek2.py
- mhkit/dolfyn/io/nortek2_lib.py
Adds logic to skip the messy header data that can accumulate during measurements collected via the Nortek software on a PC/Mac. Fix for #286
> Skip junk headers in AD2CP files

- examples/adcp_example.ipynb
- mhkit/loads/graphics.py
- mhkit/tests/river/test_io_d3d.py
Pulls to `develop` have been failing in the D3D module for an `int32` vs `int64` index in the d3d io module specifically on windows builds.
This PR ignores those differences and thereby fixes the failing tests.
Example of test failure output below:
```
================================== FAILURES ===================================
_________________ TestIO.test_create_points_array_like_inputs _________________
self = <mhkit.tests.river.test_io_d3d.TestIO testMethod=test_create_points_array_like_inputs>
def test_create_points_array_like_inputs(self):
"""
Test array-like inputs such as lists.
"""
result = river.io.d3d.create_points([1, 2], [3, 4], [5, 6])
expected = pd.DataFrame(
{"x": [1, 2, 1, 2], "y": [3, 4, 3, 4], "waterdepth": [5, 5, 6, 6]}
)
>       pd.testing.assert_frame_equal( …
```
> Fix Failing test on `develop`

- mhkit/tests/wave/io/hindcast/test_hindcast.py
- mhkit/wave/io/hindcast/hindcast.py
This PR implements to minor fixes that should have been included in #302.
- restores default for ``to_pandas`` in ``wave.io.hindcast.hindcast`` to match the behavior the previous ``as_xarray`` flag (the flag name and logic are reversed)
- updates ``as_xarray`` flag in hindcast tests to ``to_pandas``
> Fix for wave xarray conversion

- .github/workflows/main.yml
- mhkit/__init__.py
* set flag name
* use master coveralls-app action
* set v0.8.0
> CI: Coveralls flag-name (#320)

- environment.yml
- mhkit/__init__.py
- requirements.txt
- setup.py
This PR will fix testing and installation issues associated with numpy 2.0.0 until all required packages support.
> MHKiT Numpy < 2.0.0

- environment.yml
- mhkit/wave/contours.py
- requirements.txt
- setup.py
The latest version of matplotlib broke a previous check for matplotlib versions earlier than 3.8.0
This fix requires that matplotlib be at least 3.8.0 for MHKiT and removes the check.
> matplotlib >=3.8.0

- mhkit/tests/wave/test_resource_spectrum.py
- mhkit/wave/resource.py
Fix: If unnamed, set spectrum dim_0 name to "Frequency"
The surface_elevation function typically takes in a spectrum generated
by an mhkit function that sets the index/dimension name to "Frequency".
This fix handles an atypical case where the index/first dimension is
unnamed, which causes downstream issues where we are expecting a
dimension named "Frequency".
Per the [xarray DataArray documentation](https://docs.xarray.dev/en/stable/generated/xarray.DataArray.html)
an unnamed dimension starts at dim_0. If we find this case we
change the dim_0 name to "Frequency".
> Fix: Handle unnamed index/dimension in wave.resource.surface_elevation 

- .github/workflows/main.yml
- .github/workflows/pypi.yml
- README.md
- examples/qc_example.ipynb
- examples/river_example.ipynb
- examples/tidal_example.ipynb
This PR updates our git workflow to use `main` as the MHKiT default branch :
- Many modern projects use `main` as the default branch, aligning with the GitHub recommendation and broader conventions.
- There is some non-linear history in the previous rebase causing issues between `develop` & `master`
- `main` was created from the current `develop` branch creating a 1-to-1 liner history between `develop` and the new `main` branch
> Use `main` as Primary Branch

- .github/workflows/main.yml
- .github/workflows/pypi.yml
- README.md
- examples/qc_example.ipynb
- examples/river_example.ipynb
- examples/tidal_example.ipynb
This release includes significant new features, enhancements, bug fixes, and updates to improve the functionality, performance, and compatibility of MHKiT.
- Introduced a new Acoustics module to MHKiT, providing comprehensive tools for processing and analyzing passive acoustic data from hydrophone recordings.
- Designed to facilitate compliance with the IEC-TS 62600-40 standard
- Supports hydrophone models such as SoundTrap and icListen, with functionality to read, calibrate, and process hydrophone data into acoustic metrics.
- Includes functionalities for:
- Reading hydrophone data.
- Performing spectral analyses.
- spectral density (SPSD) 
- spectral density levels (SPSDL) 
- Fractional octave bands (e.g., third-octave, decidecade)
- Sound Pressure Level (SPL)
- Applying calibrations.
- …
> MHKiT 0.9.0

- mhkit/dolfyn/io/nortek2.py
Simple fix to a problem created by a previous PR. Solves Issue #366
> Avoid failing to scan very large files

- mhkit/dolfyn/io/base.py
- mhkit/dolfyn/io/nortek.py
- mhkit/dolfyn/io/nortek2.py
If a datafile is filled with bad bytes, the reader will get stuck in one of two while loops.
> Fix for corrupted Nortek files

- .github/workflows/pylint.yml
- mhkit/wave/io/hindcast/__init__.py
- mhkit/wave/io/hindcast/hindcast.py
- mhkit/wave/io/hindcast/wind_toolkit.py
This PR adds type hints to functions and will enforce linting on the wave hindcast module. 
I want to separate out the wave hindcast from the remainder of the wave module due to the long testing times on the hindcast module.
> Lint hindcast
